# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
v=np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [6]:
vect=np.arange(10,50)
vect

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [7]:
vect.shape

(40,)

5. Print the type of the previous array in question 3

In [8]:
vect.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [44]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/TANZEEL ABBAS TANNU/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/TANZEEL ABBAS TANNU/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/TANZEEL ABBAS TANNU/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compile

7. Print the dimension of the array in question 3


In [13]:
vect.ndim

1

8. Create a boolean array with all the True values

In [14]:
bol=np.array([True,True,True,True,True])
bol

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

10. Create a three dimensional array



In [17]:
np.zeros((3,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [29]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1=arr1[::-1]
arr1

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [23]:
arr1=np.zeros((10))
arr1[4]=1
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [47]:
arr = np.array([1, 2, 3, 4, 5]) 
arr.astype('float64')

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [36]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [49]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr4=np.maximum(arr1,arr2)
arr4

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [41]:
arr5=np.arange(10)
arr5[arr5%2==1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [43]:
arr5[arr5%2==1]=-1
arr5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [46]:
arr5[[5,6,7,8]]=12
arr5

array([ 0, -1,  2, -1,  4, 12, 12, 12, 12, -1])

20. Create a 2d array with 1 on the border and 0 inside

In [53]:
arr6=np.ones((5,5))
arr6[1:4:,1:4:]=0
arr6

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [57]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [86]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0:1]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [81]:
arr7=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr7[0,0:3]

array([1, 2, 3])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [89]:
arr8=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr8[1,1:2]

array([5])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [106]:
arr9=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr9[0:2,2:3:1]

array([[3],
       [6]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [52]:
arr10=np.random.randn(10,10)
print(arr10.max())
arr10.min()

2.634888105617819


-3.1400640069571057

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [115]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
arr11=a[a==b]
arr11

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [127]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where((a==b))

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [62]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names == 'Bob']

array([[-1.11495722, -0.21742177,  0.06867699, -1.65685575],
       [ 0.25994729, -0.27146934,  1.98970473, -0.08759911]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [61]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
new = (names == 'Bob') | (names == 'Will')
new

array([ True, False,  True,  True,  True, False, False])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [207]:
arr12=np.random.randint(low=1,high=15,size=(5,3))+np.random.random((5,3))
arr12

array([[10.22096415,  9.787892  , 11.27800613],
       [ 5.3166676 ,  6.49920251,  3.4743717 ],
       [14.49717325, 11.88458696,  8.38886556],
       [ 5.09048546,  8.98465506, 11.51176679],
       [ 7.60367788, 13.08457034, 13.79031834]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [209]:
arr13=np.random.randint(low=1,high=16,size=(2,2,4))+np.random.random((2,2,4))
arr13

array([[[12.79016816,  4.43550925,  4.98962679,  8.42756954],
        [10.00501491, 10.39766225,  8.06975684,  9.26070497]],

       [[ 5.52848688, 14.11594311,  4.67571776, 11.59029022],
        [10.2407691 ,  1.11712835,  2.10513296,  1.0982204 ]]])

33. Swap axes of the array you created in Question 32

In [12]:
arr13=np.array([[[12.79016816,  4.43550925,  4.98962679,  8.42756954],
        [10.00501491, 10.39766225,  8.06975684,  9.26070497]],

       [[ 5.52848688, 14.11594311,  4.67571776, 11.59029022],
        [10.2407691 ,  1.11712835,  2.10513296,  1.0982204 ]]])
arr13=np.swapaxes(arr13,1,2)
arr13

array([[[12.79016816, 10.00501491],
        [ 4.43550925, 10.39766225],
        [ 4.98962679,  8.06975684],
        [ 8.42756954,  9.26070497]],

       [[ 5.52848688, 10.2407691 ],
        [14.11594311,  1.11712835],
        [ 4.67571776,  2.10513296],
        [11.59029022,  1.0982204 ]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [226]:
arr14=np.array(range(1,11))
arr14=np.sqrt(arr14)
arr14[arr14<0.5]=0
arr14

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [13]:
arr1=np.random.randint(low=1,high=12,size=12)
arr2=np.random.randint(low=1,high=12,size=12)
arr3=np.maximum(arr1,arr2)
arr3

array([11, 10,  9,  6,  8,  9,  7,  7,  7,  9,  7, 11])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [19]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
names.sort()
names

['Bob' 'Joe' 'Will']


array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [57]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
new=np.setdiff1d(a,b)
new

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [43]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray=np.delete(sampleArray,1,1)
sampleArray=np.insert(sampleArray,1,newColumn, axis=1)
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [178]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [177]:
arr20=np.random.randint(1,100,20)
arr20.cumsum()

array([ 39,  50,  71, 157, 197, 266, 334, 393, 394, 439, 466, 560, 591,
       626, 664, 754, 759, 849, 883, 890], dtype=int32)